[dependencies]
base = "0.11.1"
xtended-text = "0.3.0"

[package]
name = "datetime"
version = "0.3.0"
description = "A library for DateTime values and manipulation in Motoko"
repository = "https://github.com/edjcase/motoko_datetime"
keywords = [ "datetime", "time", "date", "timezone" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
